### ISSUE TITLE
是否可以考虑二维码导出功能

### ISSUE THREAD

**Issue by asd8855** [rx-ts/vue#10]

**Comment by xiaokaike** [comment]
@asd8855  如何导出？

**Comment by sunxingchen1995** [comment]
可以使用canvas的toDataURL()方法，生成base64格式图片，作为a标记的href，设置a标记的download属性为你想要保存的文件名+格式。
![qq 20180703175446](https://user-images.githubusercontent.com/30208434/42212983-319cd2a2-7eea-11e8-8149-b8f6c01f3fe0.png)

**Comment by JounQin** [comment]
@asd8855 Please upgrade to 0.2.0, which is a complete rewrite from scratch, which displays `img` tag and it should be able to exported as you like.
