### ISSUE TITLE
Regarding the file name of generated QR codes.

### ISSUE THREAD

**Issue by JayCasee** [rx-ts/vue#100]
First of all, thank you for your great work...!

As a default, a generated QR code has a file name as "download.png" when a user drag a QR code out from the browser.

Is there any way to make the default file name to be different...?

**Comment by JounQin** [comment]
Actually it's not related to this lib, but of course you can custom the download image name with `download` attribute of `a` tag like following:

```vue
<!-- note the `href` attribute is required -->
<a download="qrcode-demo.png" href>
  <vue-qrcode v-bind="qrcodeProps" />
</a>
```
