### ISSUE TITLE
Typings not available

### ISSUE THREAD

**Issue by arusahni** [rx-ts/vue#102]
Hi - thanks for putting together this component! I'm attempting to use it in a Vue 2 project with TypeScript 3.9, and am getting the following error on compilation:

```
ERROR in /usr/src/app/ui/src/components/MyComponent.vue(35,23):
uiserver_1       | 35:23 Could not find a declaration file for module 'vue-qrious'. '/usr/src/app/ui/node_modules/vue-qrious/lib/cjs.js' implicitly has an 'any' type.
uiserver_1       |   Try `npm install @types/vue-qrious` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-qrious';`
uiserver_1       |   > 35 | import VueQrious from 'vue-qrious';
```

I can work around this by creating a custom `.d.ts` file in my project with `declare module 'vue-qrious';`. However, according to the `package.json`, a `types` attribute is declared.

I was wondering if the built package could be updated to export the type definitions. Thanks!

**Comment by JounQin** [comment]
Sorry for delay, it has been updated!

**Comment by arusahni** [comment]
Awesome! I'll confirm once I get a chance. Thank you.
