### ISSUE TITLE
vue 3 compatibility?

### ISSUE THREAD

**Issue by MDolega20** [rx-ts/vue#103]
![obraz](https://user-images.githubusercontent.com/44843530/99185644-80b04c00-274b-11eb-9ed0-330c503d05d8.png)

**Comment by JounQin** [comment]
Thx for reporting, I'll take a look tomorrow.

**Comment by JounQin** [comment]
@MDolega20 Please try 0.3.6-beta.0

**Comment by scholtz** [comment]
This is still the issue with v 0.4.0 

![image](https://user-images.githubusercontent.com/1223439/120921611-d129cf80-c6c4-11eb-9955-ac64957236cc.png)

**Comment by JounQin** [comment]
@scholtz Oh, sorry, please try `vue-qrcode@0.3.6-beta.0` temporarily, that PR has not been released yet because @MDolega20 hasn't confirmed if it is working, can you try and confirm that?

**Comment by muffyie** [comment]
`vue-qrcode@0.3.6-beta.0` produces new error.

![56](https://user-images.githubusercontent.com/19363684/128685245-88378230-7a25-49f8-9135-5f0c6127213f.png)

**Comment by scholtz** [comment]
I use https://github.com/scholtz/qrcode-vue3 for qr code generator and https://github.com/scholtz/qrcode-reader-vue3 for qr code scanner

```
npm install --save qrcode-reader-vue3
npm install --save qrcode-vue3
```

**Comment by JounQin** [comment]
Published `vue-qrcode@1.0.0` and `vue-qrious@2.0.0` via [vue-demi](https://github.com/vueuse/vue-demi).

They are still vue 2 and 3 compatible.

**Comment by quroom** [comment]
JounQin

I got this error
```
X [ERROR] Could not resolve "qrious"

    node_modules/vue-qrious/lib/index.js:1:19:
      1 │ import QRious from 'qrious';
        ╵                    ~~~~~~~~

  You can mark the path "qrious" as external to exclude it from the bundle, which will remove this
  error.
```

I guess it's dependency problem

**Comment by quroom** [comment]
I found that I have to install qrious dependency.. I am not sure why you made code like that..?
Is there any purpose? I guess it's better including denpency package.

**Comment by JounQin** [comment]
It is a `peer` dependency, so that you can upgrade `qrious` without changing `vue-qrious`.

**Comment by Germey** [comment]
'{ value: string; width: number; class: string; }' is not assignable to type 'IntrinsicAttributes & Partial<{}> & Omit<Readonly<ExtractPropTypes<{ version: { type: NumberConstructor; validator: (version: number) => boolean; }; ... 9 more ...; value: { ...; }; }>> & VNodeProps & AllowedComponentProps & ComponentCustomProps, never>'.
  Type '{ value: string; width: number; class: string; }' is missing the following properties from type 'Omit<Readonly<ExtractPropTypes<{ version: { type: NumberConstructor; validator: (version: number) => boolean; }; errorCorrectionLevel: { type: PropType<QRCodeErrorCorrectionLevel>; validator: (level: QRCodeErrorCorrectionLevel) => boolean; }; ... 8 more ...; value: { ...; }; }>> & VNodeProps & AllowedComponentProps ...': type, color
