### ISSUE TITLE
tslib dependency missing

### ISSUE THREAD

**Issue by krebbi** [rx-ts/vue#107]
results in 

`
ERROR in ./node_modules/vue-qrcode/lib/index.js
Module not found: Error: Can't resolve 'tslib' in '/project/node_modules/vue-qrcode/lib'
 @ ./node_modules/vue-qrcode/lib/index.js 1:0-41 88:68-74 104:23-31 104:32-40
 @ ./node_modules/babel-loader/lib??ref--4-0!./node_modules/vue-loader/lib??vue-loader-options!./resources/js/components/Profile.vue?vue&type=script&lang=js&
 @ ./resources/js/components/Profile.vue?vue&type=script&lang=js&
 @ ./resources/js/components/Profile.vue
 @ ./resources/js/routes.js
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss`

**Comment by JounQin** [comment]
Sorry, you can alias `vue-qrcode` to `vue-qrcode/lib/esm.js` temporarily.

**Comment by JounQin** [comment]
close in favor of `vue-qrcode@0.3.6`
