### ISSUE TITLE
Save QR code to specific location in vue js project

### ISSUE THREAD

**Issue by tanishq-rocks** [rx-ts/vue#144]
Is there any way to save that generated qr code to the static folder in vue js, so that user will able to access the already generated qr code in other parts of app.

**Comment by JounQin** [comment]
I'm not sure to understand what do you mean. You can right click to save the QR code image.

**Comment by tanishq-rocks** [comment]
let me explain, suppose a user want to reuse the generated QR code image or else user want to upload this image to server then how will he approach.
**User have to do :** First of all he will locate this element using selectors and then he have to write some js code for saving it to some specific folder.
**Solution :** Provide a prop named as **toFile** that prop will accept the path location where user want to save the QR code image for later uses. 
eg: 
```
<template>
  <vue-qrcode value="https://www.1stg.me" :toFile="pathName" />
</template>
<script>
import VueQrcode from 'vue-qrcode'

export default {
  data() {
    return {
      pathName: "~/asset/myqrcode.png",
    }
  },
  components: {
    VueQrcode,
  },
}
</script>
```
After it's implementation user will able to access the generated QR code image.

**Comment by JounQin** [comment]
If I understand correctly, a pathname is not possible because it's a security limitation from the browser.

**Comment by JounQin** [comment]
I add a dataURL `change` event at #146 for reusing.
