### ISSUE TITLE
Error on Nuxt 3 with 'vue-qrcode': 'QRCodeSegment' Export Not Found in 'qrcode' Module

### ISSUE THREAD

**Issue by kknono** [rx-ts/vue#178]
I am encountering an error in Nuxt 3 when trying to `import VueQrcode in the plugins. The code I used is import VueQrcode from "vue-qrcode"; export default defineNuxtPlugin(nuxtApp => { nuxtApp.vueApp.component("vue-qrcode", VueQrcode)}).` However, upon starting, I receive an error message: **[nuxt] [request error] [unhandled] [500] The requested module 'qrcode' does not provide an export named 'QRCodeSegment'.** The version I am using is `"vue-qrcode": "^2.2.1"`

**Comment by JounQin** [comment]
Please provide a minimal but runnable online reproduction.
