### ISSUE TITLE
support for vue 2.0？

### ISSUE THREAD

**Issue by pbestz** [rx-ts/vue#3]
it seems doesn't support vue 2.0.

**Comment by xiaokaike** [comment]
un support

**Comment by kyoukhana** [comment]
I am still using vue 1.0 but soon to upgrade to 2.0.  So would be nice if it had a road map to support vue 2.0

**Comment by Trim21** [comment]
in fact the component(Qrcode.vue) work fine in vue2.0 ,just copy it to a project dependent on vue2.0 is ok.
the only thing you may need to do is disable eslint...

**Comment by JounQin** [comment]
@asd8855 Please upgrade to `0.2.0`, which is a complete rewrite from scratch, which supports `Vue@2.0`.

Online DEMO: https://rx-vue.now.sh
