### ISSUE TITLE
无法显示二维码

### ISSUE THREAD

**Issue by zhu-yongqiang** [rx-ts/vue#8]
在有些安卓机上无法显示二维码

**Comment by xiaokaike** [comment]
具体机型呢？
我是用 `canvas` 来生产二维码的，是不是那些机型对 `canvas` 支持不好？

**Comment by zhu-yongqiang** [comment]
红米 型号2014813 安卓版本4.4.4 KTU84P

**Comment by zhu-yongqiang** [comment]
控制台报错error in mounted hook, 是不是1.0迁移2.0的问题？

**Comment by xiaokaike** [comment]
是的 还没有升级支持vue2.0

**Comment by liyann** [comment]
能升级支持一下vue2.0吗？

**Comment by JounQin** [comment]
@asd8855 Please upgrade to 0.2.0, which is a complete rewrite from scratch, which supports `Vue@2.0`.

Online DEMO: https://rx-vue.now.sh
