### ISSUE TITLE
how to print the qrcode in a pdf file?

### ISSUE THREAD

**Issue by fessacchiotto** [rx-ts/vue#98]
hi! how can i print the generated qrcode, for example with pdfmake, by putting it into a pdf file? or in any other way...? thanks for your help!

**Comment by JounQin** [comment]
I don't think it's related to `vue-qrcode`.

You can use [qrcode](https://github.com/soldair/node-qrcode) directly to generate `dataURL` string for `pdfmake` image node: https://pdfmake.github.io/docs/document-definition-object/images/.
